baseURL: http://shiun.me/
languageCode: zh-tw
title: Shiun
paginate: 5
theme: "PaperMod"

enableEmoji: true

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /Blog/
      weight: 10
    - identifier: About me
      name: About me
      url: https://www.linkedin.com/in/shiunchiu
      weight: 20

params:
  homeInfoParams:
    Title: Hi I'm Shiun
    Content: Backend, DevOps, Cloud and Cats!!!
  socialIcons:
    - name: "github"
      url: "https://github.com/sh1un"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/shiunchiu/"

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"
  env: production
  title: Shiun's Blog
  keywords: [Blog, Portfolio, PaperMod]
  defaultTheme: dark
  ShowShareButtons: ture
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
