baseURL: http://shiun.me/
languageCode: zh-tw
title: Shiun
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
enableEmoji: true

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /Blog/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /Tags/
      weight: 20
    - identifier: About me
      name: About me
      url: https://www.linkedin.com/in/shiunchiu
      weight: 30

params:
  homeInfoParams:
    Title: Hi I'm Shiun
    Content: Backend, DevOps, Cloud and Cats!!!
  socialIcons:
    - name: "github"
      url: "https://github.com/sh1un"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/shiunchiu/"

  assets:
    favicon: "https://github.com/sh1un/sh1un.github.io/assets/85695943/12a1e84f-ed17-4e38-8165-f67783c7f047"
  env: production
  title: Shiun's Blog
  description: "Shiun's Blog"
  keywords: [Blog, Portfolio, PaperMod]
  defaultTheme: dark
  ShowShareButtons: ture
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
