baseURL: https://shiun.me/
languageCode: zh-tw
title: Shiun
paginate: 5
theme: "PaperMod"

googleAnalytics: G-RZR8D4ERKG
disqus:
  enable: true
  shortname: shiun-me
  count: true

enableRobotsTXT: true
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: Blog
      name: Blog
      url: /Blog/
      weight: 10
    - identifier: Archive 
      name: Archives 
      url: /archives/
      weight: 20
    - identifier: Tags
      name: Tags
      url: /Tags/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 40
    - identifier: Notion
      name: Notion
      url: https://shiun.notion.site/Shiun-s-Learning-Journal-ded4cd4a3efd47b2805f2f99dee8f9a1?pvs=4
      weight: 50
    - identifier: About me
      name: About me
      url: https://www.linkedin.com/in/shiunchiu
      weight: 60

params:
  ShareButtons: ["x", "linkedin", "facebook", "telegram"]
  homeInfoParams:
    Title: Hi I'm Shiun
    Content: Backend, DevOps, Cloud and Cats!!!
  socialIcons:
    - name: "github"
      url: "https://github.com/sh1un"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/shiunchiu/"
  assets:
    favicon: "https://github.com/sh1un/sh1un.github.io/assets/85695943/12a1e84f-ed17-4e38-8165-f67783c7f047"
  env: production
  title: Shiun's Blog
  description: "Shiun's Blog"
  images:
    - https://github.com/sh1un/sh1un.github.io/assets/85695943/42e903b9-06db-4cd8-b937-590a3cb26aea
  keywords: [Blog, Portfolio, PaperMod]
  defaultTheme: auto
  ShowShareButtons: ture
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  comments: true
